name: chama
channels:
    - defaults
    - https://anaconda.org/conda-forge/pyomo
dependencies:
    - python=3.6
    - numpy
    - scipy
    - pandas
    - sphinx
    - numpydoc
    - matplotlib
    - pyomo
